package kz.jusan.cli;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        help();
        System.out.print("> ");
        String command;
        String path="."; // default current directory
        String line = input.nextLine();
        String[] query;



            try {
                while(!line.equals("exit")) {
                    query = line.split(" ");
                    command = query[0];
                    if (query.length > 1) {
                        path = query[1];
                    }
                    //Scanner sc = new Scanner(file);
                    switch (command) {
                        case "exit":
                            exit();
                            break;
                        case "help":
                            help();
                            break;
                        case "ls":
                            listDirectory(path);
                            break;
                        case "ls_py":
                            listPythonFiles(path);
                            break;
                        case "is_dir":
                            isDirectory(path);
                            break;
                        case "define":
                            define(path); break;
                        default:
                            System.out.println("No valid command found. Type help to view commands.");
                    }
                    System.out.print("> ");
                    line=input.nextLine();
                }
            } catch(Exception e) {
                e.printStackTrace();
                //System.out.println(e);
            }

    }




    // выводит список всех файлов и директорий для `path` - ls
    public static void listDirectory(String path) {
        File file = new File(path);
        File[] files = file.listFiles();
        for (File f : files) {
            System.out.print(f.getName() + " ");
        }
        System.out.println();
    };
    // выводит список файлов с расширением `.py` в `path` - ls_py
    public static void listPythonFiles(String path) {
        File file = new File(path);
        File[] files = file.listFiles();
        for (File f: files) {
            String extension = "";

            int i = f.getName().lastIndexOf('.');
            if (i > 0) {
                extension = f.getName().substring(i+1);
            }
            if(extension.equals("py")) {
                System.out.print(f.getName()+ " ");
            }
        }
        System.out.println();
    };
    // выводит `true`, если `path` это директория, в других случаях `false` - id_dir
    public static void isDirectory(String path) {
        File file = new File(path);
        if(file.isDirectory()) {
            System.out.println(true);
        } else {
            System.out.println(false);
        }
    }
    // выводит `директория` или `файл` в зависимости от типа `path` - define
    public static void define(String path) {
        File file = new File(path);
        if(file.isDirectory()) {
            System.out.println("директория");
        } else {
            System.out.println("файл");
        }
    }
    // выводит права для файла в формате `rwx` для текущего пользователя - readmod
    public static void printPermissions(String path) {};
    // устанавливает права для файла `path` - setmod
    public static void setPermissions(String path, String permissions) {};
    // выводит контент файла - cat
    public static void printContent(String path) {};
    // добавляет строке `# Autogenerated line` в конец `path` - append
    public static void appendFooter(String path) {};
    // создает копию `path` в директорию `/tmp/${date}.backup` где, date - это дата в формате `dd-mm-yyyy`. `path` может быть директорией или файлом. При директории, копируется весь контент. - bc
    public static void createBackup(String path) {};
    // выводит самое длинное слово в файле - greplong
    public static void printLongestWord(String path) {};
    // выводит список команд и их описание - help
    public static void help() {
        System.out.println("MyFS 1.0 команды:\n" +
                "ls <path>               выводит список всех файлов и директорий для `path`\n" +
                "ls_py <path>            выводит список файлов с расширением `.py` в `path`\n" +
                "is_dir <path>           выводит `true`, если `path` это директория, в других случаях `false`\n" +
                "define <path>           выводит `директория` или `файл` в зависимости от типа `path`\n" +
                "readmod <path>          выводит права для файла в формате `rwx` для текущего пользователя\n" +
                "setmod <path> <perm>    устанавливает права для файла `path`\n" +
                "cat <path>              выводит контент файла\n" +
                "append <path>           добавляет строку `# Autogenerated line` в конец `path`\n" +
                "bc <path>               создает копию `path` в директорию `/tmp/${date}.backup` где, date - это дата в формате `dd-mm-yyyy`\n" +
                "greplong <path>         выводит самое длинное слово в файле\n" +
                "help                    выводит список команд и их описание\n" +
                "exit                    завершает работу программы");
    }
    // завершает работу программы - exit
    public static void exit() {
        System.out.println("Goodbye!");
        return;
    }
}
